### ISSUE TITLE
java.lang.module.FindException

### ISSUE THREAD

**Issue by antmordel** [fvarrui/JavaPackager#106]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
How to proceed when a module is not found.

**Steps to reproduce the issue/enhancement:**

Having a minimal configuration like this

When doing `package`, it turns out to:
```
[INFO]             Executing command: /bin/sh -c cd '/Users/antmordel/example/.' && '/usr/local/Cellar/openjdk/15.0.2/libexec/openjdk.jdk/Contents/Home/bin/jdeps' -q --multi-release 15 --ignore-missing-deps --print-module-deps /Users/antmordel/example/target/example-app/example-app.app/Contents/Resources/Java/libs/*.jar /Users/antmordel/example//target/example-app-1.0.0-SNAPSHOT-runnable.jar
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module metrics.core not found, required by com.zaxxer.hikari
[ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:894)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
```
This is the dependency tree:
```
[INFO] +- org.springframework.boot:spring-boot-starter-web:jar:2.4.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.4.5:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.4.5:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.4.5:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.4.5:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.13.3:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.30:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  +- org.springframework:spring-core:jar:5.3.6:compile
[INFO] |  |  |  \- org.springframework:spring-jcl:jar:5.3.6:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.27:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-json:jar:2.4.5:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.4:compile
[INFO] |  |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.4:compile
[INFO] |  |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.11.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.11.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.4:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.11.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.4.5:compile
[INFO] |  |  \- org.glassfish:jakarta.el:jar:3.0.3:compile
[INFO] |  +- org.springframework:spring-web:jar:5.3.6:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.6:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.3.6:compile
[INFO] |     +- org.springframework:spring-aop:jar:5.3.6:compile
[INFO] |     +- org.springframework:spring-context:jar:5.3.6:compile
[INFO] |     \- org.springframework:spring-expression:jar:5.3.6:compile
[INFO] +- org.springframework.boot:spring-boot-starter-actuator:jar:2.4.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.4.5:compile
[INFO] |  |  \- org.springframework.boot:spring-boot-actuator:jar:2.4.5:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.6.6:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- org.apache.tomcat.experimental:tomcat-embed-programmatic:jar:9.0.45:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.4.5:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.4.5:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.6:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.4.5:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:3.4.5:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.6:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.4.30.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[INFO] |  |  +- org.javassist:javassist:jar:3.27.0-GA:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.22:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.2.3.Final:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  +- org.dom4j:dom4j:jar:2.1.3:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.4:compile
[INFO] |  |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.4:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:2.4.8:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.4.8:compile
[INFO] |  |  +- org.springframework:spring-orm:jar:5.3.6:compile
[INFO] |  |  \- org.springframework:spring-tx:jar:5.3.6:compile
[INFO] |  \- org.springframework:spring-aspects:jar:5.3.6:compile
[INFO] +- io.dropwizard.metrics:metrics-healthchecks:jar:3.2.4:compile
[INFO] +- com.h2database:h2:jar:1.4.200:compile
[INFO] +- org.openjfx:javafx-controls:jar:mac:16-ea+1:compile
[INFO] |  \- org.openjfx:javafx-graphics:jar:16-ea+1:compile
[INFO] +- org.openjfx:javafx-graphics:jar:mac:16-ea+1:compile
[INFO] |  \- org.openjfx:javafx-base:jar:16-ea+1:compile
[INFO] |     \- org.openjfx:javafx-base:jar:mac:16-ea+1:compile
[INFO] +- org.openjfx:javafx-fxml:jar:mac:16-ea+1:compile
[INFO] |  \- org.openjfx:javafx-controls:jar:16-ea+1:compile
[INFO] +- org.kordamp.ikonli:ikonli-core:jar:12.2.0:compile
[INFO] +- org.kordamp.ikonli:ikonli-javafx:jar:12.2.0:compile
[INFO] +- org.kordamp.ikonli:ikonli-antdesignicons-pack:jar:12.2.0:compile
[INFO] \- org.slf4j:slf4j-api:jar:1.7.30:compile
```

**What is the expected behavior?**
I know that this one is a transitive dependency. I can add it, but that won't help. I can, however, add the property:
```xml
<customizedJre>false</customizedJre>
```
And that works!

I wonder if there's an argument where I can specify a list of modules that are missing and that I want to include in the jlink process? Or better said, once I have errors like this, how could I further debug to get it working?

I've read https://github.com/fvarrui/JavaPackager/issues/45 but I think it is a bit different.

Thanks a lot, Francisco.

**Comment by fvarrui** [comment]
Hi @antmordel!
`metrics-core` library it's not being included when dependencies are copied, because its scope is [provided](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope).

I found next fragment in [com.zaxxer.HikariCP](https://search.maven.org/artifact/com.zaxxer/HikariCP/3.4.5/bundle)  `pom.xml`, which is the module that is causing the problem:
```xml
<dependency>
         <groupId>io.dropwizard.metrics</groupId>
         <artifactId>metrics-core</artifactId>
         <version>${metrics.version}</version>
         <scope>provided</scope>
         <optional>true</optional>
</dependency>
```

What happens if you add `metric-core` dependency in your `pom.xml`?

```xml
<dependency>
  <groupId>io.dropwizard.metrics</groupId>
  <artifactId>metrics-core</artifactId>
  <version>3.2.4</version>
</dependency>
```

> I know that this one is a transitive dependency. I can add it, but that won't help. I can, however, add the property:

Why won't this help?

When you set `customizedJre` to `false`, all modules will be added in the generated JRE, which is not optimal since modules that are not necessary will be included, occupying unnecessary space. The ideal is to have a minimum JRE according to our application and its dependencies.

> I wonder if there's an argument where I can specify a list of modules that are missing and that I want to include in the jlink process? Or better said, once I have errors like this, how could I further debug to get it working?

You can use `additionalModules` property to specify a list of modules to be included in the `jlink` process. This option is useful when `jdeps` can't determine modules which are necessary (maybe caused by automatic modules). But the problem here is that `jdeps` is trying to find modules which are missing, and I still haven't found a way that `jdeps` won't stop (without errors) when it can't find a module. So, in your case, the only solution is to include your transitive module as a dependency.

**Comment by antmordel** [comment]
Many thanks for your detailed answer @fvarrui! I've been trying to solve this as you mention but I get nowhere.

I added explicitly `metrics-core`, then it asked for `metrics-healthchecks`, and then it asked for `metrics-core`, again? 

Not only that, but I tried to put exclusions as well to make this more "home-managed", but with no success.

I'm pasting my current whole pom to you, just in case it helps: https://gist.github.com/antmordel/9d992c8ec9f835305bd06ec08427cced

Again, thanks a lot for your time.

**Comment by fvarrui** [comment]
I've just remember that there's another option: `modules` 😅. You can use it to specify the modules you what to include in the generated JRE, so `jdeps` call is skipped. Maybe it helps!

**Comment by antmordel** [comment]
I have thought about using `modules`... but that means getting all the needed modules... by hand? 😓 With using Spring those are a lot!

**Comment by fvarrui** [comment]
I've been making some tests with the dependencies of your `pom.xml`, and I realized that if you only exclude `com.zaxxer:HikariCP` from `org.springframework.boot:spring-boot-starter-data-jpa`:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-data-jpa</artifactId>
	<version>${spring.version}</version>
	<exclusions>
		<exclusion>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

`jdeps` and `jlink` work fine! Maybe this happens because some of the modules that HikariCP depends on are non-modular.

```
[INFO]     Copying all dependencies ...
[INFO] Copying commons-io-2.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\commons-io-2.6.jar
[INFO] Copying spring-boot-starter-web-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-web-2.4.5.jar
[INFO] Copying spring-boot-starter-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-2.4.5.jar
[INFO] Copying spring-boot-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-2.4.5.jar
[INFO] Copying spring-boot-autoconfigure-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-autoconfigure-2.4.5.jar
[INFO] Copying spring-boot-starter-logging-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-logging-2.4.5.jar
[INFO] Copying logback-classic-1.2.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\logback-classic-1.2.3.jar
[INFO] Copying logback-core-1.2.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\logback-core-1.2.3.jar
[INFO] Copying log4j-to-slf4j-2.13.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\log4j-to-slf4j-2.13.3.jar
[INFO] Copying log4j-api-2.13.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\log4j-api-2.13.3.jar
[INFO] Copying jul-to-slf4j-1.7.30.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jul-to-slf4j-1.7.30.jar
[INFO] Copying jakarta.annotation-api-1.3.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jakarta.annotation-api-1.3.5.jar
[INFO] Copying spring-core-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-core-5.3.6.jar
[INFO] Copying spring-jcl-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-jcl-5.3.6.jar
[INFO] Copying snakeyaml-1.27.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\snakeyaml-1.27.jar
[INFO] Copying spring-boot-starter-json-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-json-2.4.5.jar
[INFO] Copying jackson-databind-2.11.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jackson-databind-2.11.4.jar
[INFO] Copying jackson-annotations-2.11.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jackson-annotations-2.11.4.jar
[INFO] Copying jackson-core-2.11.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jackson-core-2.11.4.jar
[INFO] Copying jackson-datatype-jdk8-2.11.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jackson-datatype-jdk8-2.11.4.jar
[INFO] Copying jackson-datatype-jsr310-2.11.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jackson-datatype-jsr310-2.11.4.jar
[INFO] Copying jackson-module-parameter-names-2.11.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jackson-module-parameter-names-2.11.4.jar
[INFO] Copying spring-boot-starter-tomcat-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-tomcat-2.4.5.jar
[INFO] Copying jakarta.el-3.0.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jakarta.el-3.0.3.jar
[INFO] Copying spring-web-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-web-5.3.6.jar
[INFO] Copying spring-beans-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-beans-5.3.6.jar
[INFO] Copying spring-webmvc-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-webmvc-5.3.6.jar
[INFO] Copying spring-aop-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-aop-5.3.6.jar
[INFO] Copying spring-context-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-context-5.3.6.jar
[INFO] Copying spring-expression-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-expression-5.3.6.jar
[INFO] Copying spring-boot-starter-actuator-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-actuator-2.4.5.jar
[INFO] Copying spring-boot-actuator-autoconfigure-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-actuator-autoconfigure-2.4.5.jar
[INFO] Copying spring-boot-actuator-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-actuator-2.4.5.jar
[INFO] Copying micrometer-core-1.6.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\micrometer-core-1.6.6.jar
[INFO] Copying HdrHistogram-2.1.12.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\HdrHistogram-2.1.12.jar
[INFO] Copying LatencyUtils-2.0.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\LatencyUtils-2.0.3.jar
[INFO] Copying tomcat-embed-programmatic-9.0.45.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\tomcat-embed-programmatic-9.0.45.jar
[INFO] Copying spring-boot-starter-data-jpa-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-data-jpa-2.4.5.jar
[INFO] Copying spring-boot-starter-aop-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-aop-2.4.5.jar
[INFO] Copying aspectjweaver-1.9.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\aspectjweaver-1.9.6.jar
[INFO] Copying spring-boot-starter-jdbc-2.4.5.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-boot-starter-jdbc-2.4.5.jar
[INFO] Copying spring-jdbc-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-jdbc-5.3.6.jar
[INFO] Copying jakarta.transaction-api-1.3.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jakarta.transaction-api-1.3.3.jar
[INFO] Copying jakarta.persistence-api-2.2.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jakarta.persistence-api-2.2.3.jar
[INFO] Copying hibernate-core-5.4.30.Final.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\hibernate-core-5.4.30.Final.jar
[INFO] Copying jboss-logging-3.4.1.Final.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jboss-logging-3.4.1.Final.jar
[INFO] Copying javassist-3.27.0-GA.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javassist-3.27.0-GA.jar
[INFO] Copying byte-buddy-1.10.22.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\byte-buddy-1.10.22.jar
[INFO] Copying antlr-2.7.7.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\antlr-2.7.7.jar
[INFO] Copying jandex-2.2.3.Final.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jandex-2.2.3.Final.jar
[INFO] Copying classmate-1.5.1.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\classmate-1.5.1.jar
[INFO] Copying dom4j-2.1.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\dom4j-2.1.3.jar
[INFO] Copying hibernate-commons-annotations-5.1.2.Final.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\hibernate-commons-annotations-5.1.2.Final.jar
[INFO] Copying jaxb-runtime-2.3.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jaxb-runtime-2.3.4.jar
[INFO] Copying jakarta.xml.bind-api-2.3.3.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jakarta.xml.bind-api-2.3.3.jar
[INFO] Copying txw2-2.3.4.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\txw2-2.3.4.jar
[INFO] Copying istack-commons-runtime-3.0.12.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\istack-commons-runtime-3.0.12.jar
[INFO] Copying jakarta.activation-1.2.2.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\jakarta.activation-1.2.2.jar
[INFO] Copying spring-data-jpa-2.4.8.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-data-jpa-2.4.8.jar
[INFO] Copying spring-data-commons-2.4.8.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-data-commons-2.4.8.jar
[INFO] Copying spring-orm-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-orm-5.3.6.jar
[INFO] Copying spring-tx-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-tx-5.3.6.jar
[INFO] Copying slf4j-api-1.7.30.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\slf4j-api-1.7.30.jar
[INFO] Copying spring-aspects-5.3.6.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\spring-aspects-5.3.6.jar
[INFO] Copying h2-1.4.200.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\h2-1.4.200.jar
[INFO] Copying javafx-controls-16-ea+1.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-controls-16-ea+1.jar
[INFO] Copying javafx-controls-16-ea+1-win.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-controls-16-ea+1-win.jar
[INFO] Copying javafx-graphics-16-ea+1.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-graphics-16-ea+1.jar
[INFO] Copying javafx-graphics-16-ea+1-win.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-graphics-16-ea+1-win.jar
[INFO] Copying javafx-base-16-ea+1.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-base-16-ea+1.jar
[INFO] Copying javafx-base-16-ea+1-win.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-base-16-ea+1-win.jar
[INFO] Copying javafx-fxml-16-ea+1.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-fxml-16-ea+1.jar
[INFO] Copying javafx-fxml-16-ea+1-win.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\javafx-fxml-16-ea+1-win.jar
[INFO] Copying ikonli-core-12.2.0.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\ikonli-core-12.2.0.jar
[INFO] Copying ikonli-javafx-12.2.0.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\ikonli-javafx-12.2.0.jar
[INFO] Copying ikonli-antdesignicons-pack-12.2.0.jar to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\ikonli-antdesignicons-pack-12.2.0.jar
[INFO]     Dependencies copied to C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs!
[INFO]
[INFO]     Creating runnable JAR...
[INFO] Building jar: C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven-1.0.0-runnable.jar
[INFO]     Runnable jar created in C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven-1.0.0-runnable.jar!
[INFO]
[INFO]     Bundling JRE ... with C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot
[INFO]         Creating customized JRE ...
[INFO]         Getting required modules ...
[INFO]             Executing command: cmd.exe /s /c ""C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\bin\jdeps" -q --multi-release 14 --ignore-missing-deps --print-module-deps C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\libs\*.jar C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven-1.0.0-runnable.jar"
[INFO]             java.base,java.compiler,java.desktop,java.instrument,java.management.rmi,java.prefs,java.scripting,java.security.jgss,java.sql.rowset,jdk.attach,jdk.httpserver,jdk.jdi,jdk.jfr,jdk.management,jdk.net,jdk.unsupported
[INFO]         Required modules found: [java.base, java.compiler, java.desktop, java.instrument, java.management.rmi, java.prefs, java.scripting, java.security.jgss, java.sql.rowset, jdk.attach, jdk.httpserver, jdk.jdi, jdk.jfr, jdk.management, jdk.net, jdk.unsupported]
[INFO]
[INFO]         Creating JRE with next modules included: java.base,java.compiler,java.desktop,java.instrument,java.management.rmi,java.prefs,java.scripting,java.security.jgss,java.sql.rowset,jdk.attach,jdk.httpserver,jdk.jdi,jdk.jfr,jdk.management,jdk.net,jdk.unsupported
[INFO]         Using C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\jmods modules directory
[INFO]         Executing command: cmd.exe /s /c ""C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\bin\jlink" --module-path "C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot\jmods" --add-modules java.base,java.compiler,java.desktop,java.instrument,java.management.rmi,java.prefs,java.scripting,java.security.jgss,java.sql.rowset,jdk.attach,jdk.httpserver,jdk.jdi,jdk.jfr,jdk.management,jdk.net,jdk.unsupported --output C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre --no-header-files --no-man-pages --strip-debug --compress=2"
[INFO]         Removing folder [C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre\legal]
[INFO]     JRE bundled in C:\Users\fvarrui\GitHub\HelloWorldMaven\target\HelloWorldMaven\jre!
```

It would be great if we could exclude HikariCP module from dependency analysis, but include it when dependencies are copied to `libs` folder. But, I'm not sure how to achieve this.

> I have thought about using modules... but that means getting all the needed modules... by hand? 😓 With using Spring those are a lot!

Those are the modules needed for your app to generate a customized runtime without analyzing HikariCP:

```xml
<modules>
    <module>java.base</module>
    <module>java.compiler</module>
    <module>java.desktop</module>
    <module>java.instrument</module>
    <module>java.management.rmi</module>
    <module>java.prefs</module>
    <module>java.scripting</module>
    <module>java.security.jgss</module>
    <module>java.sql.rowset</module>
    <module>jdk.attach</module>
    <module>jdk.httpserver</module>
    <module>jdk.jdi</module>
    <module>jdk.jfr</module>
    <module>jdk.management</module>
    <module>jdk.net</module>
    <module>jdk.unsupported</module>
</modules>
```

**Comment by antmordel** [comment]
It's awesome how much help you put into these lines. I'm trying to investigate how could I have Spring with HikariCP imported in some different way. I will come back to you in some days. Thanks a lot.

**Comment by fvarrui** [comment]
Hi @antmordel! 
Have you been able to take a look at this?

**Comment by antmordel** [comment]
Hi @fvarrui - let's close this issue since I think the main problem is adding Spring Boot. It adds way too many transitive dependencies, and I'll need to find one by one. Nevertheless, the resulting JVM weights around 115 MB that is not "too" bad for today's networks/computers.

**Comment by fvarrui** [comment]
If I find out more about this, I'll let you know
