### ISSUE TITLE
Module org.reactivestreams not found, required by com.azure.core

### ISSUE THREAD

**Issue by treimers** [fvarrui/JavaPackager#126]
I'm submitting a maybe dumb question

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
I am trying to create an native executable with Maven for a Java project connecting to a Cosmos DB in Azure. Microsoft 3rd party libs are required and I am unable to package my small project to a native package with all libs.

My problem seems to be related to Java modules and I am not an expert on this.

**Steps to reproduce the issue/enhancement:**

1. Create a project using the pom (see below)
2. Create a main class in Source folder (see below)
3. Run "mvn package"

**What is the expected behavior?**

A native executable for the OS should be created.

**What is the current behavior?**

Compilation and creation of jar file works find. Javapackager fails when getting required module.

```
[INFO]         Getting required modules ... 
[INFO]             Executing command: /bin/sh -c cd '/Users/treimers/Documents/DPAGworkspace/azure-demo/.' && '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/bin/jdeps' -q --multi-release 11 --list-deps /Users/treimers/Documents/DPAGworkspace/azure-demo/target/deploy/osx/sacm-reader/sacm-reader.app/Contents/Resources/Java/libs/*.jar /Users/treimers/Documents/DPAGworkspace/azure-demo/target/deploy/osx/sacm-reader-1.0-SNAPSHOT-runnable.jar
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module org.reactivestreams not found, required by com.azure.core
[ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:877)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:191)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:140)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:422)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:256)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration.<init>(JdepsConfiguration.java:117)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:563)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:589)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:543)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:519)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

**pom.xml**

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>net.thorsten</groupId>
	<artifactId>sacm-reader</artifactId>
	<packaging>jar</packaging>
	<version>1.0-SNAPSHOT</version>
	<organization>
		<name>Test</name>
	</organization>
	<properties>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<junit.version>5.7.1</junit.version>
		<azure-cosmos.version>4.18.0</azure-cosmos.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>${junit.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-cosmos</artifactId>
			<version>${azure-cosmos.version}</version>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-params</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
	<build>
		<finalName>${project.artifactId}</finalName>
		<extensions>
			<!-- os maven plugin, generates the property os.detected.name with value 
				"windows", "osx" or "linux" -->
			<extension>
				<groupId>kr.motd.maven</groupId>
				<artifactId>os-maven-plugin</artifactId>
				<version>1.6.1</version>
			</extension>
		</extensions>
		<plugins>
			<!-- JavaPackager plugin used to generate native application, installers 
				and zip archive -->
			<plugin>
				<groupId>io.github.fvarrui</groupId>
				<artifactId>javapackager</artifactId>
				<version>1.6.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>package</goal>
						</goals>
						<configuration>
							<mainClass>de.deutschepost.azure.sacm.SacmReader</mainClass>
							<bundleJre>true</bundleJre>
							<generateInstaller>true</generateInstaller>
							<administratorRequired>false</administratorRequired>
							<platform>auto</platform>
							<assetsDir>src/main/deploy/package</assetsDir>
							<additionalModules>jdk.security.auth,jdk.management.agent</additionalModules>
							<createZipball>true</createZipball>
							<organizationName>${project.organization.name}</organizationName>
							<outputDirectory>${project.build.directory}/deploy/${os.detected.name}</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>
```

**Main.java**

```java
package net.thorsten;

import com.azure.cosmos.ConsistencyLevel;
import com.azure.cosmos.CosmosClient;
import com.azure.cosmos.CosmosClientBuilder;

public class Main {
	public static void main(String[] args) {
		CosmosClient client = new CosmosClientBuilder().endpoint("endpoint").consistencyLevel(ConsistencyLevel.EVENTUAL)
				.contentResponseOnWriteEnabled(true).buildClient();
		System.out.println("Connection established: " + client.toString());
	}
}
```

**What is the motivation / use case for changing the behavior?**

--

**Please tell us about your environment:**

- JavaPackager version: 1.6.0
- OS version: Mac OS X 10.13.6
- JDK version: openjdk version "16.0.2" 2021-07-20
- Build tool: 
	- [x] Maven: Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

Maybe I am doing something wrong. Any help greatly appreciated, thanks!

Cheers
Thorsten

**Comment by fvarrui** [comment]
Hi @treimers!
Nice to read you again.

> I'm submitting a maybe dumb question

Not at all.

I think that your issue is related to modular libraries which depends on non-modular libraries, so when `javapackager` calls `jdeps` in order to find out which modules has to be included in the generated JRE, it fails, as it can't find `org.reactivestreams` module.

I'm still looking for a solution to this problem. 

A work around is to set `customizedJre=false`, but it'll bundle a full JRE with your app.

I hope it helps!

**Comment by treimers** [comment]
Hi Francisco,

thank you for you quick answer, nice to meet you again here :)

Your proposal helped in my case. First  I got a java.lang.UnsupportedOperationException but after removing the line

```
<additionalModules>jdk.security.auth,jdk.management.agent</additionalModules>
```

from my pom everything worked. Great, for me this is fine.

Again, thank you very much!
Cheers
Thorsten

**Comment by fvarrui** [comment]
Great!

**Comment by lhDream** [comment]
Hi @fvarrui ！
When ```"isCustomizedJre = false"```, ```"additionalModules"``` is configured will throw exception ```"java.lang.UnsupportedOperationException (no error message)"```

**Comment by lhDream** [comment]
example: 
![image](https://user-images.githubusercontent.com/41568266/190336629-85f68494-1623-4fc9-a12d-f9ca32270aa9.png)
