### ISSUE TITLE
Support Request: Jdeps error after adding Apache POI

### ISSUE THREAD

**Issue by safferyj** [fvarrui/JavaPackager#200]
I'm submitting a…

- [ ] bug report
- [ ] feature request
- [x] other

**Short description of the issue/suggestion:**
Support Request: Jdeps error after adding Apache POI

**Steps to reproduce the issue/enhancement:**

1. Execute the mvn package goal. The JavaPackager works as expected and an executable installer is built for my project.
2. Add new feature using Apache POI and the following new Maven dependencies:

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>5.2.2</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>5.2.2</version>
		</dependency>

4. Running from Eclipse, the new Apache POI dependent features work as expected.
5. Execute the mvn package goal. There is an error at the jdeps stage. The executable installer is not built.

**What is the expected behavior?**

An executable installer is built. Before adding Apache POI the log around the jdeps stage look like this.

[INFO]     Bundling JRE ... with C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot
[INFO]         Creating customized JRE ...
[INFO]         Getting required modules ... 
[INFO]             Executing command: cmd.exe /s /c ""C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\jdeps" -q --multi-release 17 --ignore-missing-deps --print-module-deps C:\WorkingCopies\Hunter\target\Hunter\libs\*.jar C:\WorkingCopies\Hunter\target\Hunter-0.4.0-runnable.jar"
[INFO]             java.base,java.desktop,java.management,java.naming,java.scripting,java.sql
[INFO]         Required modules found: [java.base, java.desktop, java.management, java.naming, java.scripting, java.sql]

**What is the current behavior?**

After adding Apache POI, the logs around the jdeps stage look like this.

[INFO]     Bundling JRE ... with C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot
[INFO]         Creating customized JRE ...
[INFO]         Getting required modules ... 
[INFO]             Executing command: cmd.exe /s /c ""C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\jdeps" -q --multi-release 17 --ignore-missing-deps --print-module-deps C:\WorkingCopies\Hunter\target\Hunter\libs\*.jar C:\WorkingCopies\Hunter\target\Hunter-0.4.0-runnable.jar"
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module SparseBitSet not found, required by org.apache.poi.poi
[ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

Above and below.

**What is the motivation / use case for changing the behavior?**

This is a support request ;)

**Please tell us about your environment:**

- JavaPackager version: 1.6.6
- OS version: Microsoft Windows [Version 10.0.19043.1645]
- JDK version: openjdk version "17.0.3" 2022-04-19
- Build tool: 
	- [x] Maven 
	- [ ] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

I have also tried executing the jdeps statement copied from the above on the command line. Interestingly the missing module reported is different each time.

C:\WorkingCopies\Hunter>"C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\jdeps" -q --multi-release 17 --ignore-missing-deps --print-module-deps C:\WorkingCopies\Hunter\target\Hunter\libs\*.jar C:\WorkingCopies\Hunter\target\Hunter-0.4.0-runnable.jar
Exception in thread "main" java.lang.module.FindException: Module commons.math3 not found, required by org.apache.poi.poi
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)

C:\WorkingCopies\Hunter>"C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\jdeps" -q --multi-release 17 --ignore-missing-deps --print-module-deps C:\WorkingCopies\Hunter\target\Hunter\libs\*.jar C:\WorkingCopies\Hunter\target\Hunter-0.4.0-runnable.jar
Exception in thread "main" java.lang.module.FindException: Module org.apache.commons.io not found, required by org.apache.poi.poi
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)

C:\WorkingCopies\Hunter>"C:\Program Files\Eclipse Adoptium\jdk-17.0.3.7-hotspot\bin\jdeps" -q --multi-release 17 --ignore-missing-deps --print-module-deps C:\WorkingCopies\Hunter\target\Hunter\libs\*.jar C:\WorkingCopies\Hunter\target\Hunter-0.4.0-runnable.jar
Exception in thread "main" java.lang.module.FindException: Module org.apache.commons.collections4 not found, required by org.apache.poi.poi
        at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
        at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
        at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:603)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:557)
        at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:533)
        at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)

C:\WorkingCopies\Hunter>

**Comment by safferyj** [comment]
I find that the error goes away if I downgrade Apache POI to 4.1.2. Then everything works as expected.

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>4.1.2</version>
		</dependency>

		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi-ooxml</artifactId>
			<version>4.1.2</version>
		</dependency>

**Comment by fvarrui** [comment]
Hi @safferyj!
Try setting `cusromizedJre=false`. I guess that `jdeps` is not dealing fine with non modular dependencies, but I have to do some more research about this.

**Comment by safferyj** [comment]
Hi, Thanks! That fixed it. So I can either proceed with POI 4.1.2 and customizedJre=true; or with POI 5.2.2 and customizedJre=false. This Issue is good to close from my perspective. Thanks again, James

**Comment by fvarrui** [comment]
Thanks!! I hope I can improve Java runtime image generation ASAP ... see [issue-204](https://github.com/fvarrui/JavaPackager/issues/204).
