### ISSUE TITLE
Failed build under Windows

### ISSUE THREAD

**Issue by mristuccia** [fvarrui/JavaPackager#24]
Hi Fran,

Trying to build a packet under Windows now and I have a problem.
This is what I get when I try to make a build:

```
--- javapackager:0.9.4:package (bundle-for-windows) @ PhotoAnnotator ---
Packaging app for windows
[info] Removing folder [C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator]
No license file specified
Creating runnable JAR...
Building jar: C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator-1.0.1-runnable.jar
Creating Windows app bundle...
Copying all dependencies to PhotoAnnotator folder ...
Copying exiftool-lib-2.5.2.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\exiftool-lib-2.5.2.jar
Copying opencsv-5.0.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\opencsv-5.0.jar
Copying commons-lang3-3.9.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\commons-lang3-3.9.jar
Copying commons-text-1.7.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\commons-text-1.7.jar
Copying commons-beanutils-1.9.4.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\commons-beanutils-1.9.4.jar
Copying commons-logging-1.2.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\commons-logging-1.2.jar
Copying commons-collections-3.2.2.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\commons-collections-3.2.2.jar
Copying commons-collections4-4.4.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\commons-collections4-4.4.jar
Copying darcula-2018.2.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\darcula-2018.2.jar
Copying annotations-16.0.1.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\annotations-16.0.1.jar
Copying commons-io-2.6.jar to C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\commons-io-2.6.jar
Copying additional resources
Bundling JRE ... with C:\Program Files\jdk-13.0.2
Getting required modules ... 
[info] Executing command: cmd.exe /X /C ""C:\Program Files\jdk-13.0.2\bin\jdeps" -q --multi-release 13 --ignore-missing-deps --print-module-deps C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\libs\*.jar C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator-1.0.1-runnable.jar"
[info] java.base,java.desktop,java.scripting,java.sql
- Modules: [java.base, java.desktop, java.scripting, java.sql, jdk.zipfs]
Creating JRE with next modules included: java.base,java.desktop,java.scripting,java.sql,jdk.zipfs
[info] Executing command: cmd.exe /X /C ""C:\Program Files\jdk-13.0.2\bin\jlink" --module-path "C:\Program Files\jdk-13.0.2\jmods" --add-modules java.base,java.desktop,java.scripting,java.sql,jdk.zipfs --output C:\Users\mristuccia\Developer\PhotoAnnotator\target\PhotoAnnotator\jre --no-header-files --no-man-pages --strip-debug --compress=2"
VersionInfo [companyName=Marco Ristuccia, copyright=Marco Ristuccia, fileDescription=PhotoAnnotator, fileVersion=1.0.0.0, internalName=PhotoAnnotator, language=null, originalFilename=PhotoAnnotator.exe, productName=PhotoAnnotator, productVersion=1.0.0.0, trademarks=null, txtFileVersion=1.0.1, txtProductVersion=1.0.1]
Platform-specific work directory already exists: C:\Users\mristuccia\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/C:/Users/mristuccia/.m2/repository/com/thoughtworks/xstream/xstream/1.4.8/xstream-1.4.8.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
launch4j: Compiling resources
launch4j: C:\Users\mristuccia\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\windres.exe: icon file `C:\Users\mristuccia\Developer\PhotoAnnotator\src\main\resources\PhotoAnnotator.icns' does not contain icon data
launch4j: Generated resource file...

launch4j: LANGUAGE 0, 1
1 VERSIONINFO
FILEVERSION 1, 0, 0, 0
PRODUCTVERSION 1, 0, 0, 0
FILEFLAGSMASK 0
FILEOS 0x40000
FILETYPE 1
{
 BLOCK "StringFileInfo"
 {
  BLOCK "040904E4"
  {
   VALUE "CompanyName", "Marco Ristuccia"
   VALUE "FileDescription", "PhotoAnnotator"
   VALUE "FileVersion", "1.0.1"
   VALUE "InternalName", "PhotoAnnotator"
   VALUE "LegalCopyright", "Marco Ristuccia"
   VALUE "LegalTrademarks", ""
   VALUE "OriginalFilename", "PhotoAnnotator.exe"
   VALUE "ProductName", "PhotoAnnotator"
   VALUE "ProductVersion", "1.0.1"
  }
 }
BLOCK "VarFileInfo"
{
VALUE "Translation", 0x0409, 0x04E4
}
}1 RCDATA BEGIN "jre\0" END
18 RCDATA BEGIN "1\0" END
30 RCDATA BEGIN "2\0" END
1 24 "C:\\Users\\mristuccia\\Developer\\PhotoAnnotator\\target\\assets\\PhotoAnnotator.exe.manifest"
1 ICON DISCARDABLE "C:\\Users\\mristuccia\\Developer\\PhotoAnnotator\\src\\main\\resources\\PhotoAnnotator.icns"
21 RCDATA BEGIN "http://java.com/download\0" END
20 RCDATA BEGIN "32\0" END
101 RCDATA BEGIN "An error occurred while starting the application.\0" END
102 RCDATA BEGIN "This application was configured to use a bundled Java Runtime Environment but the runtime is missing or corrupted.\0" END
103 RCDATA BEGIN "This application requires a Java Runtime Environment\0" END
104 RCDATA BEGIN "The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted.\0" END
17 RCDATA BEGIN "true\0" END
15 RCDATA BEGIN "com.marcoristuccia.photoannotator.PhotoAnnotator\0" END
16 RCDATA BEGIN "exiftool-lib-2.5.2.jar;opencsv-5.0.jar;commons-lang3-3.9.jar;commons-text-1.7.jar;commons-beanutils-1.9.4.jar;commons-logging-1.2.jar;commons-collections-3.2.2.jar;commons-collections4-4.4.jar;darcula-2018.2.jar;annotations-16.0.1.jar;commons-io-2.6.jar\0" END


net.sf.launch4j.BuilderException: net.sf.launch4j.ExecException: Exec failed (1): C:\Users\mristuccia\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\MRISTU~1\AppData\Local\Temp\launch4j5154200424852081323rc C:\Users\MRISTU~1\AppData\Local\Temp\launch4j16907059095660829957o
	at net.sf.launch4j.Builder.build(Builder.java:149)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.doExecute(Launch4jMojo.java:432)
	at com.akathist.maven.plugins.launch4j.Launch4jMojo.execute(Launch4jMojo.java:321)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.twdata.maven.mojoexecutor.MojoExecutor.executeMojo(MojoExecutor.java:119)
	at io.github.fvarrui.javapackager.PackageMojo.createWindowsApp(PackageMojo.java:661)
	at io.github.fvarrui.javapackager.PackageMojo.execute(PackageMojo.java:336)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: net.sf.launch4j.ExecException: Exec failed (1): C:\Users\mristuccia\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\MRISTU~1\AppData\Local\Temp\launch4j5154200424852081323rc C:\Users\MRISTU~1\AppData\Local\Temp\launch4j16907059095660829957o
	at net.sf.launch4j.Util.exec(Util.java:156)
	at net.sf.launch4j.Cmd.exec(Builder.java:215)
	at net.sf.launch4j.Builder.build(Builder.java:100)
	... 28 more
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 35.141 s
Finished at: 2020-03-29T23:09:39+02:00
Final Memory: 26M/78M
------------------------------------------------------------------------
Failed to execute goal io.github.fvarrui:javapackager:0.9.4:package (bundle-for-windows) on project PhotoAnnotator: Failed to build the executable; please verify your configuration. net.sf.launch4j.ExecException: Exec failed (1): C:\Users\mristuccia\.m2\repository\net\sf\launch4j\launch4j\3.12\launch4j-3.12-workdir-win32\bin\windres.exe --preprocessor=type -J rc -O coff -F pe-i386 C:\Users\MRISTU~1\AppData\Local\Temp\launch4j5154200424852081323rc C:\Users\MRISTU~1\AppData\Local\Temp\launch4j16907059095660829957o -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

And this is the plugin configuration I'm using (tried with 0.9.2, 0.9.3.and 0.9.4):

```XML
<plugin>
    <groupId>io.github.fvarrui</groupId>
    <artifactId>javapackager</artifactId>
    <version>0.9.4</version>
    <executions>
        <execution>
            <id>bundle-for-windows</id>
            <phase>package</phase>
            <goals>
                <goal>package</goal>
            </goals>
            <configuration>
                <mainClass>com.marcoristuccia.photoannotator.PhotoAnnotator</mainClass>
                <displayName>PhotoAnnotator</displayName>
                <organizationName>Marco Ristuccia</organizationName>
                <organizationUrl>http://www.marcoristuccia.com/it</organizationUrl>
                <iconFile>${project.build.resources[0].directory}/PhotoAnnotator.icns</iconFile>
                <bundleJre>true</bundleJre>
                <platform>auto</platform>
                <administratorRequired>false</administratorRequired>
                <generateInstaller>true</generateInstaller>
                <additionalModules>
                    <param>jdk.zipfs</param>
                </additionalModules>
            </configuration>
        </execution>
    </executions>
</plugin>
<plugin>
```

Any idea?

Thanks in advance.

Best,
marco

**Comment by fvarrui** [comment]
Maybe the icon file type! It has to be a `ico` file on Windows. You can locate your icons in your project's root folder in this way, so you won't have to change the POM to adapt it to other platforms:
```
<project>/
└── assets/
	├── linux/
	│   └── ${name}.png     # on GNU/Linux it has to be a png image
	├── macosx/
	│   └── ${name}.icns    # on Mac OS X it has to be a icns file
	└── windows/
	    └── ${name}.ico     # on Windows it has to be a ico file
```

**Comment by mristuccia** [comment]
Yes, it was simply the icon file. Thank you!

Stay safe,
marco

**Comment by fvarrui** [comment]
Yes, I stay at home. Thanks!
