### ISSUE TITLE
Task 'CopyLibs' does not grab libraries from the correct directory

### ISSUE THREAD

**Issue by adermont** [fvarrui/JavaPackager#241]
I'm submitting a…

- [x] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**

When I run my own 'packageMyApp' task, it ends with an Exception like "module emojijava can't be found". This module is not a regular Java module, it's been tuned on-the-fly by another gradle plugin named 'ExtraJavaModuleInfo' (see https://github.com/jjohannes/extra-java-module-info).

**Steps to reproduce the issue/enhancement:**

1. Install OpenJDK 18.0.1.1 into `D:/openjdk-18.0.1.1_windows-x64_bin`
2. Checkout project at 'https://github.com/adermont/samples/tree/main/myapp'
3. Run `gradle wrapper`
4. Run `gradle packageMyApp`

**What is the expected behavior?**

I think class `io.github.fvarrui.javapackager.gradle.CopyDependencies` has not correct behavior
because it copies libraries from the default configuration instead of looping among project's configurations
to find out whether some transforms have been done on default dependencies JARs.

But maybe there's a problem in the ExtraJavaModuleInfo plugin, which is expected to update the default configuration
with the new JARs' location?

**What is the current behavior?**

Libraries tuned by the ExtraJavaModuleInfo plugin are converted into modules and then they are stored in the ".gradle/transforms-3" cache directory, not in the regular ".gradle/jars-2" cache directory. When I configure my Eclipse .classpath with "gradle eclipse" command, everything is going well and my referenced libraries in eclipse's classpath have a MANIFEST file containing 'Automatic-Module-Name: XXXXXX' directive. But when I package my application with both JavaPackager and ExtraJavaModuleInfo, libraries copied by task 'copyLibs' of JavaPackager do not contain t

**Do you have outputs, screenshots, demos or samples which demonstrate the problem or enhancement?**

> Using packager io.github.fvarrui.javapackager.packagers.WindowsPackager
Creating app ...
    Initializing packager ...
        PackagerSettings [outputDirectory=D:\Java\samples\samples\myapp\build, licenseFile=null, iconFile=null, generateInstaller=true, forceInstaller=false, mainClass=com.myapp.EmojiWebExtractorTool, name=myapp, displayName=Emoji Web Extractor, version=1.0, description=Emoji Web Extractor, url=null, administratorRequired=false, organizationName=ACME, organizationUrl=, organizationEmail=, bundleJre=true, customizedJre=true, jrePath=null, jdkPath=D:\Java\openjdk-18.0.1.1_windows-x64_bin\jdk-18.0.1.1, additionalResources=[], modules=[], additionalModules=[emojijava, org.json], platform=windows, envPath=null, vmArgs=[], runnableJar=null, copyDependencies=true, jreDirectoryName=jre, winConfig=WindowsConfig [icoFile=null, headerType=gui, companyName=ACME, copyright=ACME, fileDescription=Emoji Web Extractor, fileVersion=1.0.0.0, internalName=myapp, language=null, originalFilename=myapp.exe, productName=myapp, productVersion=1.0.0.0, trademarks=null, txtFileVersion=1.0, txtProductVersion=1.0, disableDirPage=true, disableProgramGroupPage=true, disableFinishedPage=true, disableRunAfterInstall=true, disableWelcomePage=true, createDesktopIconTask=true, generateSetup=true, generateMsi=true, generateMsm=false, msiUpgradeCode=b0938e69-b104-4e3a-8ddc-9886595ecd0c, wrapJar=true, setupLanguages={english=compiler:Default.isl, spanish=compiler:Languages\Spanish.isl}, setupMode=installForAllUsers, signing=null, registry=Registry [entries=[]], removeOldLibs=false, exeCreationTool=launch4j, vmLocation=null], linuxConfig=null, macConfig=null, createTarball=false, createZipball=false, extra={}, useResourcesAsWorkingDir=true, assetsDir=D:\Java\samples\samples\myapp\assets, classpath=null, jreMinVersion=18, manifest=Manifest [additionalEntries={}, sections=[]], additionalModulePaths=[D:\Java\samples\samples\myapp\build\myapp\libs], fileAssociations=null, packagingJdk=D:\Java\openjdk-18.0.1.1_windows-x64_bin\jdk-18.0.1.1, scripts=Scripts [bootstrap=null, preInstall=null, postInstall=null]]
    Packager initialized!
    Creating app structure ...
        App folder created: D:\Java\samples\samples\myapp\build\myapp
        Assets folder created: D:\Java\samples\samples\myapp\build\assets
    App structure created!
    Resolving resources ...
        No license file specified
        Copying resource [/windows/default-icon.ico] to file [D:\Java\samples\samples\myapp\build\assets\myapp.ico]
        Icon file resolved: D:\Java\samples\samples\myapp\build\assets\myapp.ico
        Effective additional resources [D:\Java\samples\samples\myapp\build\assets\myapp.ico]
    Resources resolved!
    Copying additional resources
        Copying file [D:\Java\samples\samples\myapp\build\assets\myapp.ico] to folder [D:\Java\samples\samples\myapp\build\myapp]
    All additional resources copied!
    Copying all dependencies ...
    Dependencies copied to D:\Java\samples\samples\myapp\build\myapp\libs!
    Creating runnable JAR...
    Runnable jar created in D:\Java\samples\samples\myapp\build\myapp-1.0-runnable.jar!
    Bundling JRE ... with D:\Java\openjdk-18.0.1.1_windows-x64_bin\jdk-18.0.1.1
        Creating customized JRE ...
        Getting required modules ...
            Executing command: cmd.exe /s /c "D:\Java\openjdk-18.0.1.1_windows-x64_bin\jdk-18.0.1.1\bin\jdeps -q --multi-release 18 --ignore-missing-deps --print-module-deps --module-path D:\Java\samples\samples\myapp\build\myapp\libs D:\Java\samples\samples\myapp\build\myapp\libs\*.jar D:\Java\samples\samples\myapp\build\myapp-1.0-runnable.jar"

> Exception in thread "main" java.lang.module.FindException: Module emojijava not found, required by com.myapp
          at java.base/java.lang.module.Resolver.findFail(Resolver.java:893)
          at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
          at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
          at java.base/java.lang.module.Configuration.resolve(Configuration.java:421)
          at java.base/java.lang.module.Configuration.resolve(Configuration.java:255)
          at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
          at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:604)
          at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:558)
          at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:534)
          at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:49)

**What is the motivation / use case for changing the behavior?**

There are plenty of existing JARs that are not modularized yet. For module suppliers, we can't access old JAR libraries
from our Java modules unless we make them as modules with ExtraJavaModuleInfo plugin.

**Please tell us about your environment:**

- JavaPackager version: 1.6.6
- OS version: Windows 11
- JDK version: 18.0.1.1
- Build tool: Gradle 7.4.6

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)

**Comment by fvarrui** [comment]
Hi @adermont!

I'm not sure how to say to JavaPackager where to copy "modularized" JARs from. Some clue? Maybe we can add a new option to the plugin for specifying the `libs` folder which has to be bundled with the app (`libsDir=path/to/libs/folder`), instead of just copying dependencies. This way you can create your own `libs` folder.

I plan to add support for Java Modules in v1.7.0, and I've been analyzing the situation. I think that modifying JARs is not a good idea as they could be signed. And what happen with multi-release JARs? (I have not tried `ExtraJavaModuleInfo`, so I don't know how it deals with this problems).

> There are plenty of existing JARs that are not modularized yet. For module suppliers, we can't access old JAR libraries
from our Java modules unless we make them as modules with ExtraJavaModuleInfo plugin.

I don't agree with this statement, because if you specify your JARs using the `--module-path` argument, not modularized JARs are treated as automatic modules, all their classes are exported and you can access to all of them. What's more, if the `Automatic-Module-Name` property is not in the **MANIFEST.MF** file, the JVM uses the JAR file name as module name.

**Comment by adermont** [comment]
Hi Francisco, thank you for your reply.

I think you're right, modularizing JARs on-the-fly is not really a good idea. I just couldn't figure out how to do other way. Finally I've found another solution. I felt into many many problems with the `eclipse` gradle plugin, but now all is working fine and my app is packaged :) 

I'm using JavaFX modules and everything is working, even if you said modules are not fully supported yet in JavaPackager v1.6. I will publish my app soon at [https://github.com/adermont/smsbr-desktop](https://github.com/adermont/smsbr-desktop). Maybe people experiencing same problems could have a look on my [build.gradle](https://github.com/adermont/smsbr-desktop/blob/main/build.gradle) file to figure out how to configure their JavaFX projects in Eclipse. Here is just a part of how I solved my problems:

```// This code was very error-prone because some libs in the ModulePath 
// were considered as modules at compile-time whereas they are regular JARs.
// Then Eclipse couldn't see dependencies and told me that classes were not accessible by my module.
plugins.withType(JavaPlugin).configureEach {
    java {
        modularity.inferModulePath = true
    }
}
```
I've replaced the code above by:

```eclipse {
    classpath {
        file {
            whenMerged {
            	def libphonenumber = entries.find { it.path.contains 'libphonenumber' }
            	libphonenumber.entryAttributes['module'] = 'true'
            	
            	def libemoji = entries.find { it.path.contains 'emoji-java' }
            	libemoji.entryAttributes['module'] = 'true'
            }
        }
    }
}
```

I'd prefer closing this issue since I believe there's no good solution to the problem mentionned and finally it was just a configuration problem of my project.

**Comment by fvarrui** [comment]
Hi @adermont!
Thanks so much for sharing your solution with the JavaPackager community
