### ISSUE TITLE
Resolving dependency configuration 'default' is not allowed as it is defined as 'canberesolved=false'.

### ISSUE THREAD

**Issue by amariottini** [fvarrui/JavaPackager#315]
I'm submitting a…

- [X] bug report
- [ ] feature request
- [ ] other

**Short description of the issue/suggestion:**
When building a project with Gradle 8 I have this error:
Resolving dependency configuration 'default' is not allowed as it is defined as 'canberesolved=false'.

**Steps to reproduce the issue/enhancement:**
Take a project working with JP 1.7.0/1.7.1-SNAPSHOT and Gradle <= 7.6, upgrade to Gradle 8.

**Please tell us about your environment:**

- JavaPackager version: 1.7.0/1.7.1-SNAPSHOT
- OS version: MacOS 10.15.7
- JDK version: 11
- Build tool: 
	- [ ] Maven 
	- [X] Gradle 

**Other information** (e.g. related issues, suggestions how to fix, links for us to have context)
It seem the solution is to change the configuration name in file CopyDependencies.java on line 38.
Change configuration to runtimeClasspath:
`copyLibsTask.from(project.getConfigurations().getByName("runtimeClasspath"));`

**Comment by fvarrui** [comment]
Hi @amariottini!
By any chance, do you know if changing to `runtimeClasspath` is working with older Gradle versions?

**Comment by fvarrui** [comment]
Hi @amariottini!

I've just replaced `default` with `runtimeClasspath` as you suggested and it seems to be working fine with Gradle 6.9.3 and 8.1.1.
This change will be released to Maven Central as 1.7.2, but you can try SNAPSHOT version `1.7.2-20230505.095442-5`:

```groovy
buildscript {
	repositories {
		maven {
			url "https://oss.sonatype.org/content/repositories/snapshots"
		}
	}
	dependencies {
		classpath 'io.github.fvarrui:javapackager:1.7.2-20230505.095442-5'
	}
}
```

**Comment by amariottini** [comment]
I tried the snapshot ad it almost works, except for this (in the meantime I moved to Apple Silicon):

 ```
Executing command: /bin/sh -c cd '/Users/andrea/Projects/firmasmartcardagent/.' && 'bless' --folder /Volumes/AgentFirma --openfolder /Volumes/AgentFirma
        bless: The 'openfolder' is not supported on Apple Silicon devices.
    DMG image generation failed due to: Command execution failed: bless --folder /Volumes/AgentFirma --openfolder /Volumes/AgentFirma
org.codehaus.plexus.util.cli.CommandLineException: Command execution failed: bless --folder /Volumes/AgentFirma --openfolder /Volumes/AgentFirma
	at io.github.fvarrui.javapackager.utils.CommandUtils.executeOnDirectory(CommandUtils.java:20)
	at io.github.fvarrui.javapackager.utils.CommandUtils.execute(CommandUtils.java:30)
	at io.github.fvarrui.javapackager.packagers.GenerateDmg.doApply(GenerateDmg.java:137)
	at io.github.fvarrui.javapackager.packagers.GenerateDmg.doApply(GenerateDmg.java:22)
	at io.github.fvarrui.javapackager.packagers.ArtifactGenerator.apply(ArtifactGenerator.java:44)
	at io.github.fvarrui.javapackager.packagers.Packager.generateInstallers(Packager.java:440)
	at io.github.fvarrui.javapackager.gradle.AbstractPackageTask.doPackage(AbstractPackageTask.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:166)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70)
	at org.gradle.internal.Either$Right.fold(Either.java:175)
	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:76)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:37)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:94)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:47)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:324)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:317)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

And with this version I don't have the problem reported in the other issue:
**>Plugin with id 'io.github.fvarrui.javapackager.plugin' not found.**

**Comment by fvarrui** [comment]
😨 Ok, it seems that something has changed in `bless` command for M1 devices. I've just found out that if architecture is x64 we can use: `bless --folder /Volumes/AgentFirma --openfolder /Volumes/AgentFirma`, but for ARM64 we have to omit `--openfolder /Volumes/AgentFirma` when blessing the app folder. 

I'm going to implement a fix right now and upload a snapshot, but I need you to test it, please  I'll try to tell you something in a few minutes.

**Comment by fvarrui** [comment]
I'm a bit confused 😕  ... please, could you tell what this Java instruction returns on your system?
```java
String osArchitecture = System.getProperty("os.arch");
System.out.println(osArchitecture);
```

**Comment by amariottini** [comment]
It prints "x86_64"

Maybe I have a x86_64 JVM.... 

But why you need to bless the volume?

**Comment by fvarrui** [comment]
As you can read in the comment, it "makes the top window open itself on mount"

**Comment by fvarrui** [comment]
> It prints "x86_64"
> 
> Maybe I have a x86_64 JVM....

It's a bit weird 😅 ... is that possible?

**Comment by fvarrui** [comment]
Please, take a look at this: 
https://stackoverflow.com/questions/69497067/java-sdk-reporting-wrong-architecture-on-mac-m1
... it seems to be the same issue.

**Comment by amariottini** [comment]
IntelliJ runs with this environment:
Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

But Gradle project is scoped to Java 1.8 and I use the Oracle JVM and this is only for x86_64.
In which JVM does the plugin run?

**Comment by fvarrui** [comment]
I think that it does in the Gradle one.

**Comment by fvarrui** [comment]
Are you open to use another JDK or you have to use Oracle JDK?

**Comment by fvarrui** [comment]
> I think that it does in the Gradle one.

I mean ... run `gradle -version` or `gradlew -version` and I think that is the JDK version used for building your project.

**Comment by amariottini** [comment]
Very strange.. `./gradlew --version` (I use grade wrapper) prints:
```
JVM:          20.0.1 (Oracle Corporation 20.0.1+9-29)
OS:           Mac OS X 13.3.1 aarch64
```

**Comment by fvarrui** [comment]
Anyway, I guess we can change the code so that the process continues even if the blessing fails, notifying the exception as a warning. What do you think?

**Comment by amariottini** [comment]
I think you need to find a more reliable way to test OS architecture.
In this case you need OS arch and not JVM arch, you are executing a shell command, the problem could reoccur in other cases.

About ignoring the error: is ok as a temporary solution

**Comment by amariottini** [comment]
I found exists the `arch` command, but I don't know from which OS version...

**Comment by Osiris-Team** [comment]
@fvarrui Having the same issue. These are my plugins:
<details>
<summary>gradle.settings</summary>

```groovy
buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
    dependencies {
        classpath 'com.github.johnrengelman:shadow:7.1.1'
        classpath 'io.github.fvarrui:javapackager:1.7.0'
    }
}

plugins {
    id 'com.github.johnrengelman.shadow' version '7.1.1'
    id 'java'
    id 'maven-publish'
}

apply plugin: 'com.github.johnrengelman.shadow'
apply plugin: 'io.github.fvarrui.javapackager.plugin'

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}
dependencies {
    implementation 'com.github.Osiris-Team:Desku:0.5.8'
    implementation 'commons-io:commons-io:2.6'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.7.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.7.0'
}
test {
    useJUnitPlatform()
}

import io.github.fvarrui.javapackager.gradle.PackageTask;
import io.github.fvarrui.javapackager.model.*;

group = 'com.osiris'
version = '1.0.0'
description = 'Desku example app.'
sourceCompatibility = '1.17'
compileJava.options.encoding = 'UTF-8'

javapackager {
    mainClass = 'com.osiris.deskuapp.Main'
    additionalResources = [ file('src/main/resources/info.txt') ]
    bundleJre = true
    generateInstaller = true
    vmArgs = ["-Djava.library.path=."]
    administratorRequired = false
}
// Output to build/libs/<project-name>.jar
shadowJar {
    archiveBaseName.set(rootProject.name)
    archiveClassifier.set('')
    archiveVersion.set('')
}

task packageForWindows(type: PackageTask, dependsOn: build) {
    description = 'Packages the application as a native Windows executable and bundles it in a zipball'
    platform = 'windows'
    createZipball = true
    winConfig {
        vmArgs = ["-Dprism.maxvram=512m -XX:+UseG1GC"]
        generateSetup = true
        generateMsi = true
        icoFile = file("windows/HelloWorldGradle.ico")
        setupMode = SetupMode.askTheUser
        removeOldLibs = true
        disableDirPage = false
        disableFinishedPage = false
        disableWelcomePage = false
        createDesktopIconTask = false
    }
}

task packageForLinux(type: PackageTask, dependsOn: build) {
    description = 'Packages the application as a native GNU/Linux executable and bundles it in a tarball'
    platform = 'linux'
    bundleJre = true
    createTarball = true
    scripts {
        bootstrap = file('assets/bootstrap.sh')
    }
}

task packageForMac(type: PackageTask, dependsOn: build) {
    description = 'Packages the application as a native Mac OS app and bundles it in a tarball'
    platform = 'mac'
    createTarball = true
    scripts {
        bootstrap = file('assets/bootstrap.sh')
    }
    macConfig {
        infoPlist.additionalEntries = '''
			<key>LSUIElement</key>
			<true/>
		'''
    }
}

task packageForAllPlatforms(dependsOn: [ packageForWindows, packageForMac, packageForLinux ]) {
    description = 'Packages the application for all platforms'
    group = 'JavaPackager'
}

```
</details>

I am on Java 17, Windows 10 and Gradle 8.1.1.

**Comment by Osiris-Team** [comment]
That did it for me thanks!

**Comment by fvarrui** [comment]
I close this issue as the main reason is fixed in JP 1.7.2, which was already released and I'll open a new issue for the "blessing" bug.

**Comment by fvarrui** [comment]
> I close this issue as the main reason is fixed in JP 1.7.2, which was already released and I'll open a new issue for the "blessing" bug.

I was wrong, this change didn't release with 1.7.2 so I'll keep this issue open until then.

**Comment by amariottini** [comment]
I tried 1.7.3-20230505.163915-1 and it works with Gradle 7.6 and 8.1.1

**Comment by amariottini** [comment]
@fvarrui Any news about 1.7.3 release?
At the moment I'm forced to use the latest SNAPSHOT from https://oss.sonatype.org/content/repositories/snapshots
